// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"459","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"EventInformation","status":true,"description":"イベントの頭上に文字を表示したい時に使います","parameters":{}},
{"name":"Ticker","status":true,"description":"ティッカープラグイン","parameters":{"Opacity":"127","DisplayDuration":"100","ToggleDuration":"20"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"FAR_ConfusionMove","status":true,"description":"プレイヤーを酔っ払い移動させるプラグインです。","parameters":{"ControlSwitchNo":"2","PlayerBalloonNo":"1"}},
{"name":"FAR_JumpMove","status":true,"description":"キャラクターをジャンプ移動させるプラグインです。","parameters":{"ControlSwitchNo":"3","PlayerJumpOn":"true"}},
{"name":"FAR_SelfSwitchCustom","status":true,"description":"セルフスイッチ変更時のマップリフレッシュを変更イベントのみにします。","parameters":{"ApplyFlag":"4"}},
{"name":"FAR_DashCustom","status":true,"description":"ダッシュの速度を変更したり、加減速率の概念を加えたりするプラグインです。","parameters":{"ControlSwitchNo":"5","DashSpeedVariableNo":"2"}}
];
